spring:
  application:
    name: flipkart-application

  datasource:
    url: jdbc:postgresql://localhost:5432/flipkartdb   # PostgreSQL URL
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update        # create, update, validate, none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"          # Expose all actuator endpoints
      base-path: /actuator      # Base path for actuator