spring:
  application:
    name: flipkart-application

  datasource:
    url: jdbc:postgresql://localhost:5432/flipkartdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true